add lecture2.md
yukigithub5/RaiseTech pull request #1
Opened 2023-12-20 12:07 UTC by yukigithub5

第二回課題提出させて頂きます。ご確認お願いします。

2023-12-20 12:57 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！

2023-12-20 12:57 UTC, MasatoshiMizumoto commented on lecture2.md
> + 6.GitHub　での PR 作成デモンストレーション
このほうが良いと思います！
```suggestion
 1. バージョン管理  
 2. Git  
 3. Markdown  
 4. チーム開発におけるバージョン管理  
 5. 開発で役立つ Github TIPS  
 6. GitHub での PR 作成デモンストレーション  
```

2023-12-20 12:57 UTC, MasatoshiMizumoto commented on lecture2.md
> + 作業は難しかった。
句点読点以外での改行は違和感があるので、ここは意識したほうが良いかなと思いました！

2023-12-21 01:21 UTC, yukigithub5 commented on lecture2.md
> + 作業は難しかった。
確認ありがとうございます。
承知しました。修正します。

2023-12-21 01:21 UTC, yukigithub5 commented
修正を行いました。
ご確認お願いします。

2023-12-21 01:31 UTC, MasatoshiMizumoto approved these changes
LGTM!

2023-12-21 01:32 UTC, MasatoshiMizumoto commented
OKです！私のGitHub IDをCollaboratorに追加するようお願いします！！
それでマージできるようになります！

2023-12-21 01:55 UTC, yukigithub5 commented
Collaboratorに追加させて頂きました。
<img width="602" alt="image" src="https://github.com/yukigithub5/raisetech2/assets/154067664/9e3ab417-e421-417a-b0a9-99f8ce620a41">

2023-12-21 09:25 UTC, merged